### ISSUE TITLE
ESPN authentication no more working!

### ISSUE THREAD

**Issue by farazirfan47** [cwendt94/espn-api#99] opened 2020-08-10 16:55 UTC
Looks like ESPN applied google recaptcha, Is it still possible to get login via script?

**Comment by cwendt94** [comment] 2020-08-10 20:16
I am still able to login to my private league using `League(league_id=1245, year=2018, espn_s2='ASCWDWheghjwwqfwjqhgjkjgegkje', swid='{03JFJHW-FWFWF-044G}')` and `League(league_id=1245, year=2018, username='userName', password='pass')`

Which way are you using to authenticate?

**Comment by farazirfan47** [comment] 2020-08-11 07:21
@cwendt94 I was trying to log in with username and password, did you try to login with that?

**Comment by cwendt94** [comment] 2020-08-11 15:30
On my account I was able to login with username and password. What errors are you seeing? It could be a error getting your credentials or the two cookies `espn_s2` and `swid` are not enough to authenticate your account.

**Comment by cwendt94** [comment] 2020-09-10 02:09
Duplicate of #100. Moving authentication talks to that issue

**Closed by cwendt94** 2020-09-10 02:09 UTC
